home:
    resource: ../src/Controller/Main/MainController.php
    type: attribute

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        de: '/de/'
        en: '/en/'
    name_prefix: 'app_'