home:
    resource: ../src/Controller/Main/MainController.php
    type: attribute

controllers:
    resource: routing.controllers
    type: attribute
    prefix:
        de: '/de/'
        en: '/en/'
    name_prefix: 'app_'